// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace aDealerEDVMS.Repository.ToanHH.Models;

public partial class DealersHht
{
    public int DealerId { get; set; }

    public string DealerName { get; set; }

    public string DealerCode { get; set; }

    public string Address { get; set; }

    public string Phone { get; set; }

    public string Email { get; set; }

    public DateOnly? EstablishedDate { get; set; }

    public bool? IsActive { get; set; }

    public int? TotalStaff { get; set; }

    public decimal? Rating { get; set; }

    public DateTime? LastAudit { get; set; }

    public int CreatedBy { get; set; }

    public virtual ICollection<DealerContractsHht> DealerContractsHhts { get; set; } = new List<DealerContractsHht>();
}