// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace aDealerEDVMS.Repository.ToanHH.Models;

public partial class DealerContractsHht
{
    public int ContractId { get; set; }

    public int ToandealerId { get; set; }

    public DateOnly StartDate { get; set; }

    public DateOnly EndDate { get; set; }

    public decimal ContractValue { get; set; }

    public string Status { get; set; }

    public DateTime? CreatedAt { get; set; }

    public virtual DealersHht Toandealer { get; set; }
}